- name: app set-up
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: node js
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs
    
- name: mongodb setup
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb-setup

- name: systemctl start service 
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd    
    