- name: app set-up
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: python
  ansible.builtin.import_role:
    name: common
    tasks_from: python

- name: systemctl start service 
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd    
    